name: MitMirror-CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Look for style errors with Flake8
        run: flake8 mitmirror tests
      
      - name: Look for auto format errors with black
        run: black --check --diff mitmirror tests
      
      - name: Run tests with pytest
        run: |
          echo 'SECRET_KEY="secret-key-default-for-tests"' >> .secrets.toml;
          echo 'CONNECTION_STRING="sqlite:///mitmirror.db"' >> .secrets.toml;
          pytest -v -x --cov --junitxml=test-result.xml
      
      - name: publish junit results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-result.xml
          check_name: Test Result (Python ${{matrix.python-version}})
